### ISSUE TITLE
Docs Bug

### ISSUE THREAD

**Issue by MaximKing1** [Androz2091/discord-giveaways#208] opened 2021-02-05 12:29 UTC
Under the 
Other examples:
there is the 2 working ones for me when i click the Enmap one and Mongoose one they dont lead to anywhere, didnt know if it was a error just letting you know.

**Comment by Nico105** [comment] 2021-02-05 12:36
It is not a bug, the links just lead to the master branch, but the master branch does not have the example files yet because they are in the develop branch.
When the develop branch gets merged into master then the error won't happen anymore.
Just click onto the "examples" folder in the dev branch manually.

**Closed by Nico105** 2021-02-05 12:36 UTC

**Comment by MaximKing1** [comment] 2021-02-05 12:37
thanks just letting you know

**Comment by MaximKing1** [comment] 2021-02-05 12:37
umm in dev for me none in examples

**Comment by Nico105** [comment] 2021-02-05 12:56
![image](https://user-images.githubusercontent.com/63612668/107036371-d7ad4680-67b9-11eb-96dd-39c699545b6a.png)
![image](https://user-images.githubusercontent.com/63612668/107036436-f27fbb00-67b9-11eb-89d7-36d2bc233f5b.png)
https://github.com/Androz2091/discord-giveaways/tree/develop/examples/custom-databases

**Comment by MaximKing1** [comment] 2021-02-05 12:59
Sorry didn’t see that I refreshed page and worked I think it went back to master went I went on before...


Sent from Mail for Windows 10
