### ISSUE TITLE
Time not updating

### ISSUE THREAD

**Issue by HeemPlayz** [Androz2091/discord-giveaways#91] opened 2020-08-03 14:28 UTC
Hi There,

So, when I create a new giveaway, I make to update the time every 10 seconds, but every time it updates only once then stay the same, I use quick,db as in the example, and here is the start giveaway code
```js
const ms = require('ms');
const config = require("./../config.json");

const db = require("quick.db")
const Prefix = require("../models/prefix.js")
exports.run = async (client, message, args, Discord) => {
  
Prefix.findOne({
    guildID: message.guild.id,
    prefix: "."
  }, (err,prefixes) => {

  if(!prefixes) {
	  const newPrefix = new Prefix({
		  _id: mongoose.Types.ObjectId(),
		  guildID: msg.guild.id,
		  prefix: "."
	  })
	  newPrefix.save()
  } else {
let prefix = prefixes.prefix
    // If the member doesn't have enough permissions
    if(!message.member.hasPermission('MANAGE_MESSAGES') && !message.member.roles.cache.some((r) => r.name === "Giveaways")){
      let embed = new Discord.MessageEmbed()
        .setColor("#f30707")
        .setDescription("You don't have `Manage Messages` permission");
        return message.channel.send(embed);
    }

    // Giveaway channel
   /* let giveawayChannel = message.mentions.channels.first();
    // If no channel is mentionned
    if(!giveawayChannel){
        return message.channel.send(':x: You have to mention a valid channel!');
    }*/
  
  let embed = new Discord.MessageEmbed()
        .setColor("#f30707")
        .setDescription(`Example: \`${prefix}gstart 1d 1 Nitro\``);

    // Giveaway duration
    let giveawayDuration = args[0];
    // If the duration isn't valid
    if(!giveawayDuration || isNaN(ms(giveawayDuration))){
        return message.channel.send(embed);
    }

    // Number of winners
    let giveawayNumberWinners = args[1];
    // If the specified number of winners is not a number
    if(isNaN(giveawayNumberWinners) || (parseInt(giveawayNumberWinners) <= 0)){
        return message.channel.send(embed);
    }

    // Giveaway prize
    let giveawayPrize = args.slice(2).join(' ');
    // If no prize is specified
    if(!giveawayPrize){
        return message.channel.send(embed);
    }

    // Start the giveaway
    client.giveawaysManager.start(message.channel, {
        // The giveaway duration
        time: ms(giveawayDuration),
        // The giveaway prize
        prize: giveawayPrize,
        // The giveaway winner count
        winnerCount: giveawayNumberWinners,
        // Who hosts this giveaway
        hostedBy: message.author,
        // Messages
        messages: {
            giveaway: "🎉🎉 **GIVEAWAY** 🎉🎉",
            giveawayEnded: "🎉🎉 **GIVEAWAY ENDED** 🎉🎉",
            timeRemaining: "Time remaining: **{duration}**!",
            inviteToParticipate: "React with 🎉 to participate!",
            winMessage: "Congratulations, {winners}! You won **{prize}**!",
            embedFooter: "Giveaways",
            noWinner: "Giveaway cancelled, no valid participations.",
            hostedBy: "Hosted by: {user}",
            winners: "winner(s)",
            endedAt: "Ended at",
            units: {
                seconds: "seconds",
                minutes: "minutes",
                hours: "hours",
                days: "days",
                pluralS: false // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
            }
        }
    });

   // message.channel.send(`Giveaway started in ${giveawayChannel}!`);
  }
})
};

module.exports.help = {
  name: "gstart"
}```
So why?

**Comment by Androz2091** [comment] 2020-08-04 11:44
Can you send the code which creates your GiveawaysManager instance? (the `new GiveawaysManager()`)

**Comment by HeemPlayz** [comment] 2020-08-04 17:03
Here it is
```js
const { GiveawaysManager } = require("discord-giveaways");
if(!db.get("giveaways")) db.set("giveaways", []);

const GiveawayManagerWithOwnDatabase = class extends GiveawaysManager {

    // This function is called when the manager needs to get all the giveaway stored in the database.
    async getAllGiveaways(){
        // Get all the giveaway in the database.
        return db.get("giveaways");
    }

    // This function is called when a giveaway needs to be saved in the database (when a giveaway is created or when a giveaway is edited).
    async saveGiveaway(messageID, giveawayData){
        // Add the new one.
        db.push("giveaways", giveawayData);
        return true;
    }

    async editGiveaway(messageID, giveawayData){
        // Gets all the current giveaways
        const giveaways = db.get("giveaways");
        // Remove the old giveaway from the current giveaways ID
        const newGiveawaysArray = giveaways.filter((giveaway) => giveaway.messageID !== messageID);
        // Push the new giveaway to the array
        newGiveawaysArray.push(giveawayData);
        // Save the updated array
        db.set("giveaways", newGiveawaysArray);
        return true;
    }

    // This function is called when a giveaway needs to be deleted from the database.
    async deleteGiveaway(messageID){
        // Remove the giveaway from the array
        const newGiveawaysArray = db.get("giveaways").filter((giveaway) => giveaway.messageID !== messageID);
        // Save the updated array
        db.set("giveaways", newGiveawaysArray);
        return true;
    }

};

const manager = new GiveawayManagerWithOwnDatabase(client, {
    storage: false,
    updateCountdownEvery: 10000,
    default: {
        botsCanWin: false,
        exemptPermissions: ["MANAGE_MESSAGES", "ADMINISTRATOR"],
        embedColor: "#FF0000",
        reaction: "🎉"
    }
});
client.giveawaysManager = manager;```

**Comment by HeemPlayz** [comment] 2020-08-09 17:10
Any help?

**Comment by fxrefly** [comment] 2020-08-15 07:24
I'm having the same issue.

**Comment by HeemPlayz** [comment] 2020-08-15 10:09
I don't know why @Androz2091 isn't responding.

**Comment by Androz2091** [comment] 2020-09-05 15:04
I am not able to reproduce the bugs. Can you give more information, such as your discord.js or quick.db version?

**Comment by HeemPlayz** [comment] 2020-09-06 05:24
I use discord.js 12.3.1 / quick.db 7.1.1
And when the time stops, I can't end the giveaway and tell me that it doesn't exist

**Comment by NicoHd105** [comment] 2020-12-20 00:18
If you use the latest versions of these modules now, then are you still facing this issue?
If not then please provide a solution/conclusion if you found one and close this issue.

**Comment by Androz2091** [comment] 2021-01-09 15:34
Closed due to inactivity

**Closed by Androz2091** 2021-01-09 15:34 UTC
Labels: bug, cannot reproduce
