### ISSUE TITLE
footer bug

### ISSUE THREAD

**Issue by BeLikeThugi** [Androz2091/discord-giveaways#417] opened 2022-01-15 15:34 UTC
it doesnt write the amount of winners that are eligible to win in the normal giveaways' footer. it shows only in drops.

**Comment by Nico105** [comment] 2022-01-15 16:28
Did you edit the footer message?

**Comment by BeLikeThugi** [comment] 2022-01-15 17:53
no i didnt

**Comment by Nico105** [comment] 2022-01-15 18:07
you're on v5.0.1?

**Comment by BeLikeThugi** [comment] 2022-01-16 07:44
Yes.

**Comment by Nico105** [comment] 2022-01-16 20:44
did you extend the `generateEmbed` function?

**Comment by Nico105** [comment] 2022-01-23 15:43
@BeLikeThugi

**Comment by Nico105** [comment] 2022-01-29 18:23
Please send your giveaway start options.
And maybe a screenshot of the embed

**Comment by Nico105** [comment] 2022-02-04 12:52
If no additional information will be provided then I will have to close this issue, since it's not really reproduceable for me.

**Closed** 2022-02-26 12:16 UTC
Labels: bug
